/* generated using openapi-typescript-codegen -- do not edit */
export type { Company } from './models/Company';
export type { CompanyRepresentative } from './models/CompanyRepresentative';
export type { CompanyRepresentativeRequest } from './models/CompanyRepresentativeRequest';
export type { Direction } from './models/Direction';
export type { DirectionRequest } from './models/DirectionRequest';
export { EducationLevelEnum } from './models/EducationLevelEnum';
export type { ExtendedUser } from './models/ExtendedUser';
export type { ExtendedUserRequest } from './models/ExtendedUserRequest';
export type { Faculty } from './models/Faculty';
export type { FacultyRequest } from './models/FacultyRequest';
export type { InrtuDivision } from './models/InrtuDivision';
export type { InrtuDivisionRequest } from './models/InrtuDivisionRequest';
export type { Internship } from './models/Internship';
export type { InternshipRequest } from './models/InternshipRequest';
export { InternshipTypeEnum } from './models/InternshipTypeEnum';
export type { PatchedCompanyRepresentativeRequest } from './models/PatchedCompanyRepresentativeRequest';
export type { PatchedDirectionRequest } from './models/PatchedDirectionRequest';
export type { PatchedFacultyRequest } from './models/PatchedFacultyRequest';
export type { PatchedInrtuDivisionRequest } from './models/PatchedInrtuDivisionRequest';
export type { PatchedInternshipRequest } from './models/PatchedInternshipRequest';
export type { PatchedSkillRequest } from './models/PatchedSkillRequest';
export type { PatchedSpecialityRequest } from './models/PatchedSpecialityRequest';
export type { PatchedStreamRequest } from './models/PatchedStreamRequest';
export type { PatchedStudentGroupRequest } from './models/PatchedStudentGroupRequest';
export type { PatchedStudentGroupYearMetaRequest } from './models/PatchedStudentGroupYearMetaRequest';
export type { PatchedStudentRequest } from './models/PatchedStudentRequest';
export type { PatchedStudentsInternshipReportRequest } from './models/PatchedStudentsInternshipReportRequest';
export type { PatchedStudentsInternshipRequest } from './models/PatchedStudentsInternshipRequest';
export { RoleEnum } from './models/RoleEnum';
export type { Skill } from './models/Skill';
export type { SkillRequest } from './models/SkillRequest';
export type { Speciality } from './models/Speciality';
export type { SpecialityRequest } from './models/SpecialityRequest';
export type { Stream } from './models/Stream';
export type { StreamRequest } from './models/StreamRequest';
export type { Student } from './models/Student';
export type { StudentGroup } from './models/StudentGroup';
export type { StudentGroupRequest } from './models/StudentGroupRequest';
export type { StudentGroupYearMeta } from './models/StudentGroupYearMeta';
export type { StudentGroupYearMetaRequest } from './models/StudentGroupYearMetaRequest';
export type { StudentRequest } from './models/StudentRequest';
export type { StudentsInternship } from './models/StudentsInternship';
export type { StudentsInternshipReport } from './models/StudentsInternshipReport';
export type { StudentsInternshipReportRequest } from './models/StudentsInternshipReportRequest';
export { StudentsInternshipReportStatusEnum } from './models/StudentsInternshipReportStatusEnum';
export type { StudentsInternshipRequest } from './models/StudentsInternshipRequest';
export { StudentsInternshipStatusEnum } from './models/StudentsInternshipStatusEnum';
export type { Teacher } from './models/Teacher';
